services:
  formulosity:
    restart: unless-stopped
    image: formulosity:latest
    build:
      context: .
      additional_contexts:
        api: ./api
        ui: ./ui
    ports:
      - "8081:8081"
    init: true
    environment:
      - LOG_LEVEL=debug
      - DATABASE_TYPE=sqlite # postgres|sqlite
      - DATABASE_URL=/data/sqlite3/formulosity.db
      - SURVEYS_DIR=/data/surveys
      - CONSOLE_API_ADDR=http://127.0.0.1:8081/api
      - IRON_SESSION_SECRET=e75af92dffba8065f2730472f45f2046941fe35f361739d31992f42d88d6bf6c
      - HTTP_BASIC_AUTH=user:pass
    volumes:
      - ./api/surveys:/data/surveys
      - ./api/sqlite3:/data/sqlite3
